name: symon
version: '0.1'
synopsis: Minimal implementation(s) of the classic electronic memory game.
description: |
  This was an attempt to submit a ludum dare entry in 2h.
  It is also a nice kata (exercise) for practising haskell game development.
  And could be used to demonstrate different libraries and approaches.

  Currently there is one implementation, a simple ansi command line one.
  Improvements, new implementations and project collaborators are welcome.

category: Development
author: Simon Michael
maintainer: simon@joyful.com
copyright: ! 'Copyright: (c) 2016 Simon Michael'
license: GPL-3
homepage: https://github.com/simonmichael/symon

dependencies:
- base >=4.7 && <5
- ansi-terminal
- monad-loops
- random

executables:
  symon:
    main: Main.hs
    source-dirs: src
