name: symon
version: '0.1'
synopsis: Minimal implementation(s) of the classic electronic memory game.
description: |
  This was an attempt to submit a ludum dare entry in 2h.
  It is also a nice kata (exercise) for practising haskell game development
  and/or demonstrating different libraries and approaches.
  Improvements, new implementations and co-developers are welcome.

  Currently there is one implementation, a minimal ansi command line one.
  See README for more.

category: Development
author: Simon Michael
maintainer: simon@joyful.com
copyright: ! 'Copyright: (c) 2016 Simon Michael'
license: GPL-3
homepage: https://github.com/simonmichael/symon

dependencies:
- base >=4.7 && <5
- ansi-terminal
- monad-loops
- random

source-dirs: src

executables:
  symon-ansi:
    main: symon-ansi.hs
