name: symon
version: '0.1.0.0'
synopsis: Simple project template from stack
description: Please see README.md
category: Development
author: Simon Michael
maintainer: simon@joyful.com
copyright: ! 'Copyright: (c) 2016 Simon Michael'
license: GPL-3
#homepage: https://github.com/simonmichael/symon#readme

dependencies:
- base >=4.7 && <5
- monad-loops
- random

executables:
  symon:
    main: Main.hs
    source-dirs: src
